const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetMaxSpeed
	];
};
self.C3_JsPropNameTable = [
	{Fondo1: 0},
	{Sólido: 0},
	{Piso1: 0},
	{Piso2: 0},
	{Piso3: 0},
	{Piso4: 0},
	{Piso5: 0},
	{Piso6: 0},
	{Piso7: 0},
	{Piso8: 0},
	{Piso9: 0},
	{Piso10: 0},
	{Piso11: 0},
	{Piso12: 0},
	{Piso13: 0},
	{Piso14: 0},
	{Piso15: 0},
	{Piso16: 0},
	{Piso17: 0},
	{Piso18: 0},
	{Piso19: 0},
	{Piso20: 0},
	{Piso21: 0},
	{Piso22: 0},
	{Arbol: 0},
	{Arbusto1: 0},
	{Arbusto2: 0},
	{Arbusto3: 0},
	{Hongo1: 0},
	{Hongo2: 0},
	{Hongo3: 0},
	{SaltoATravés: 0},
	{Puente: 0},
	{Caja1: 0},
	{Caja2: 0},
	{Cerca: 0},
	{Moneda: 0},
	{Plataforma: 0},
	{Girar: 0},
	{DesplazarHasta: 0},
	{Personaje: 0},
	{Arbol2: 0},
	{Teclado: 0},
	{Fondo2: 0},
	{Espinas: 0},
	{Seno: 0},
	{Ascensor: 0},
	{Llave: 0},
	{Puerta: 0},
	{Cascada1: 0},
	{Cascada2: 0},
	{Audio: 0},
	{Fondoitems: 0},
	{Texto1: 0},
	{Texto2: 0},
	{Sine: 0},
	{Enemigo: 0},
	{Monedas: 0},
	{Tiempo: 0}
];

self.InstanceType = {
	Fondo1: class extends self.ITiledBackgroundInstance {},
	Piso1: class extends self.ISpriteInstance {},
	Piso2: class extends self.ISpriteInstance {},
	Piso3: class extends self.ISpriteInstance {},
	Piso4: class extends self.ISpriteInstance {},
	Piso5: class extends self.ISpriteInstance {},
	Piso6: class extends self.ISpriteInstance {},
	Piso7: class extends self.ISpriteInstance {},
	Piso8: class extends self.ISpriteInstance {},
	Piso9: class extends self.ISpriteInstance {},
	Piso10: class extends self.ISpriteInstance {},
	Piso11: class extends self.ISpriteInstance {},
	Piso12: class extends self.ISpriteInstance {},
	Piso13: class extends self.ISpriteInstance {},
	Piso14: class extends self.ISpriteInstance {},
	Piso15: class extends self.ISpriteInstance {},
	Piso16: class extends self.ISpriteInstance {},
	Piso17: class extends self.ISpriteInstance {},
	Piso18: class extends self.ISpriteInstance {},
	Piso19: class extends self.ISpriteInstance {},
	Piso20: class extends self.ISpriteInstance {},
	Piso21: class extends self.ISpriteInstance {},
	Piso22: class extends self.ISpriteInstance {},
	Arbol: class extends self.ISpriteInstance {},
	Arbusto1: class extends self.ISpriteInstance {},
	Arbusto2: class extends self.ISpriteInstance {},
	Arbusto3: class extends self.ISpriteInstance {},
	Hongo1: class extends self.ISpriteInstance {},
	Hongo2: class extends self.ISpriteInstance {},
	Hongo3: class extends self.ISpriteInstance {},
	Puente: class extends self.ISpriteInstance {},
	Caja1: class extends self.ISpriteInstance {},
	Caja2: class extends self.ISpriteInstance {},
	Cerca: class extends self.ISpriteInstance {},
	Moneda: class extends self.ISpriteInstance {},
	Personaje: class extends self.ISpriteInstance {},
	Arbol2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Fondo2: class extends self.ITiledBackgroundInstance {},
	Espinas: class extends self.ISpriteInstance {},
	Ascensor: class extends self.ISpriteInstance {},
	Llave: class extends self.ISpriteInstance {},
	Puerta: class extends self.ISpriteInstance {},
	Cascada1: class extends self.ISpriteInstance {},
	Cascada2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Fondoitems: class extends self.ISpriteInstance {},
	Texto1: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Enemigo: class extends self.ISpriteInstance {}
}